dist: xenial
install:
  - wget -O hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.56.3/hugo_extended_0.56.3_Linux-64bit.tar.gz
  - tar -xvf hugo.tar.gz

script:
  - ./hugo

deploy:
  local_dir: public
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master